Switch to ST_retcode over STDLL for subcommands. Fixes Windows build.
svm_train.ado gives identical output as on OS X and Linux.

(hunting this down took fooooorever; I was getting an obscure
.\_svm.c(301) : error C2071: 'func' : illegal storage class
which turned out to be because STDLL declares the storage class:

Also fix the new testing make targets for Windows.